


INSERT INTO `contents` (`id`, `created_at`, `updated_at`, `PageName`, `HeadingOne`, `HeadingTwo`, `HeadingThree`, `HeadingFour`, `ContentOne`, `ContentTwo`, `ContentThree`, `ContentFour`, `PhoneOne`, `PhoneTwo`, `PhoneThree`, `HeaderImageUrl`) VALUES
(1, '2020-09-10 00:02:35', '2020-11-23 11:30:02', 'About', 'About Us', 'images/About/AboutImg.jpg', NULL, NULL, 'Established in 2016, Honeyworld Zimbabwe (Private) Limited (HWZ), is a social enterprise whose aim is to support the marginalized rural smallholder farmers of Zimbabwe to venture into beekeeping as an income generating activity and as a way to foster environmental conservation. Our objective is to impact the communities we work with by providing them sustainable livelihoods through providing beekeeping training, equipment and advice on modern beekeeping while also assuring them of a ready market for their honey. We contribute to economic development by increasing rural farming families’ incomes through a sustainable supply chain, producing high quality honey, which we buy at fair market prices. We promote the conservation of the environment by encouraging the combining of beekeeping with other farming activities to reap the benefits of cross pollination by bees. We partner with various organizations, individuals and business owners that are motivated by the opportunity to make a financial contribution and improve the lives of people in the communities where we work through donations or as social impact investors. We therefore enable our funders to fulfill their social and philanthropic goals by partnering with us. We are committed to producing top quality, pure unadulterated honey which is affordable and suitable for both local and foreign markets. Guided by our values, we endeavor to uphold the highest quality standards to provide a carefully processed and professionally packaged product. In addition to our pure natural honey, we also offer beekeeping training and we supply beekeeping equipment to passionate beekeepers and those already in the trade. Our firm belief in teamwork and collaboration enables us to handhold and mentor passionate beekeepers until they become successful and self-sufficient. Please keep watching this space for our project activities, innovative products and services. Feel free to like our posts, leave comments and make inquiries, our dedicated staff will ensure to respond within the shortest possible time. Every Blessing! HWZ Team', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, '2020-09-10 00:51:20', '2020-09-10 00:51:20', 'Bee Removal', 'Bee Removals', NULL, NULL, NULL, 'We are expects in all bee removal humanely. We always perform a live bee removal of honey bees. upon request anywhere In Harare,Bulawayo and Mutare .', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(3, '2020-09-10 00:51:47', '2020-09-10 00:51:47', 'Apiary', 'Apiary Setup', NULL, NULL, NULL, 'We help and we have teams to help you setup.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, '2020-09-10 00:52:12', '2020-09-10 00:52:12', 'Training', 'Beekeeping Training', NULL, NULL, NULL, 'Call us for details, we desire to see more people.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, '2020-09-10 00:52:41', '2020-09-10 00:52:41', 'Equipment', 'Bee keeping Equipment', NULL, NULL, NULL, 'We provide hives and hive tools -Honey Processing Equipment .', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, '2020-09-10 00:53:48', '2020-09-10 00:53:48', 'Sustainable', 'Sustainable', NULL, NULL, NULL, 'We understand that sustainable economic development means creating financial value. It means improving social conditions in a way that supports and not exploit the environment. We have a commitment to ensure sustainable livelihoods while preserving the environment, with emphasis on the marginalised rural communities of Zimbabwe. Less.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, '2020-09-10 00:54:54', '2020-09-10 00:54:54', 'Contact', 'Need a Quick Query', NULL, NULL, NULL, 'You can ask us anything that is of your choice, our staff work 24/7 and they are available to help you anytime of your choice.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, '2020-09-10 00:02:35', '2020-11-23 11:19:50', 'Home', 'Creative solutions, Honey World.', 'images/Slides/SlideOne.jpg', 'images/Slides/SlideTwo.jpg', 'images/Slides/SlideThree.jpg', 'Our objective is to impact the communities we work with by providing them sustainable livelihoods through providing beekeeping training,\r\nequipment and advice on modern beekeeping while also assuring them of a ready market for their honey', 'images/Home/ProductsImg.jpg', 'images/Home/ServicesImg.jpg', 'images/Home/StrategyImg.jpg', NULL, NULL, NULL, 'images/Home/ImpactImg.jpg');




INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Alpha', 'alflanquit@gmail.com', NULL, '$2y$10$GcGh6hav4/C8Op69N6mtueH895EjJKvpZIlyvyPeDugeacfF9mSgK', NULL, '2020-09-09 23:50:16', '2020-09-09 23:50:16'),
(2, 'tamuka magondo', 'tamuka263@gmail.com', NULL, '$2y$10$Fn.LH2.o8BMvYxKosCAtaOacfXTFLlH7w/sTJ0HseZInhjrxX.xI.', 'RROYhhB1BBTDGV592rZVvwvUdw6O1isWCD8qxsGYFRondBvxzlhLPBU1AMdl', '2020-09-09 23:50:16', '2020-09-09 23:50:16'),
(3, 'Tawanda Masango', 'tgmasango@gmail.com', NULL, '$2y$10$xgvRW4N0jIF14SsES8iDkewahvZly.KF4uXw/OnbQoV1a3h1F7RrK', NULL, NULL, NULL),
(4, 'Robinson Gezimati', 'robgez@gmail.com', NULL, '$2y$10$J8qlyR2HBM7P0yUcm45/te5xPc5QMu2lYP7QcuCZpeX5jYSkOnEgW', NULL, NULL, NULL);



COMMIT;

